Iter13
ilya-burinskiy/urlshort pull request #13
Opened 2023-12-11 16:47 UTC by ilya-burinskiy

2023-12-14 22:15 UTC, maxlyaptsev requested changes

2023-12-14 22:15 UTC, maxlyaptsev commented on internal/app/storage/map.go
> +type MapStorage map[string][2]string
```suggestion
type MapStorage map[string]Link
```
лучше использовать понятные типы, тяжело разобраться что такое 0 и 1

2023-12-14 22:15 UTC, maxlyaptsev commented on internal/app/storage/file.go
> +	file, err := os.OpenFile(fs.filePath, os.O_RDONLY|os.O_CREATE, 0666)
файл нужно закрывать после использования - defer file.Close()

2023-12-14 22:15 UTC, maxlyaptsev commented on cmd/shortener/main.go
> +	if config.DatabaseDSN != "" {
```suggestion
	if config.UseDatabase() {
```

2023-12-14 22:15 UTC, maxlyaptsev commented on cmd/shortener/main.go
> +	} else if config.FileStoragePath != "" {
```suggestion
	} else if config.UseFiles() {
```

2023-12-14 22:15 UTC, maxlyaptsev commented on cmd/shortener/main.go
> +	var fs *storage.FileStorage
Как можно сделать лучше
Для этого много чего нужно переписать, но вот идея как сделать код проще и очевидней
```go
if useDatabase {
    storage := database.New()
} else {
    storage := inmemory.New()
}
```
(псевдокод)
т.е. создать структуру которая будет поддерживать единый интерфейс, в зависимости от настроек передавать storage, а внутренним реализациям будет не важно что это за хранилище т.к. они будут использлвать интерфейс

2023-12-15 07:59 UTC, ilya-burinskiy commented on cmd/shortener/main.go
> +	var fs *storage.FileStorage
Ну я попытался что-то такое сделать через такой интерфейс
```go
type Storage interface {
	FindByOriginalURL(ctx context.Context, originalURL string) (models.Record, error)
	FindByShortenedPath(ctx context.Context, shortenedPath string) (models.Record, error)
	Save(ctx context.Context, record models.Record) error
	BatchSave(ctx context.Context, records []models.Record) error
}
```
но проблема в том, что inmemory storage надо дампить куда-то, а для database нужно закрывать соединение. И вот тут я не очень понимаю как лучше: добавить еще два метода `Dump()` и `Close()` в интерфейс `Storage` или оставить как есть (т.е. когда мне нужно вызвать `Dump()` или `Close()` я явно делаю каст интерфейса к определенному типу)

2023-12-18 13:19 UTC, maxlyaptsev commented on cmd/shortener/main.go
> +	var fs *storage.FileStorage
Можно сделать эти методы пустые. Можно сделать несколько интерфейсов со встраиванием
Например 
```go
type Dumper interface {
 Dump() bool
}
type Storage interface {
Dumper
Closer
}
```

Кто-то не делал явно сохранение данных в базу данных, а использовал один дампер, который использует в качестве данных память, а сохраняет либо в базу данных либо в файлы. Так что вариантов решения множество. Я просто предложил другой - да, эти хранилища не очень хорошо подводятся под один интерфейс, поэтому тут по желанию.

2023-12-18 13:20 UTC, maxlyaptsev approved these changes

2023-12-18 15:31 UTC, merged