Iter5
ilya-burinskiy/urlshort pull request #5
Opened 2023-11-05 09:47 UTC by ilya-burinskiy

2023-11-05 20:26 UTC, maxlyaptsev requested changes

2023-11-05 20:26 UTC, maxlyaptsev commented on cmd/shortener/flags.go
> +package main
По структуре проекта можно почитать тут - https://github.com/golang-standards/project-layout/blob/master/README.md#go-directories

В cmd должен лежать только исполняемый main.go, остальной код должен лежать в отдельных пакетах в internal

2023-11-05 20:26 UTC, maxlyaptsev commented on cmd/shortener/main.go
> +var storage = make(Storage)
глобальные переменные опасны и дают всякому кто их использует доступ к данным. Т.е. потенциально в любом участке этого пакета можно стереть или мутировать мапу. Разделение на пакеты из первого моего комментария уже пошатнет возможность использовать storage с маленькой буквы, а открытие его как публичной переменной даст возможность изменять еще и в любом месте проекта, в том числе из внешних библиотек. Нужно вызывать конструктор явно

2023-11-05 20:26 UTC, maxlyaptsev commented on cmd/shortener/handlers.go
> +// NOTE: to mock randomHex in tests
правильно было бы вынести генератор числа в отдельный пакет или структуру, объявить интерфейс и добавить этот интерфейс как зависимость в ручку сокращения ссылки. Далее по интерфейсу сгенерировать мок https://github.com/uber-go/mock и использовать его в тестах

2023-11-05 20:36 UTC, maxlyaptsev commented on cmd/shortener/handlers.go
> +// NOTE: to mock randomHex in tests
Либо можно исползовать кастомный rand для тестов, с использованием заранее заданного seed.
```
r := rand.New(rand.NewSource(1))
fmt.Print(r.Int()) 
```

2023-11-07 15:59 UTC, maxlyaptsev requested changes

2023-11-07 15:59 UTC, maxlyaptsev commented on internal/app/services/create_shortened_url_service.go
> +package services
имена файлов в go не должны содержать подчеркивания или любые другие символы (исключение _test)

2023-11-07 15:59 UTC, maxlyaptsev commented on internal/app/storage/storage.go
> +var storage = make(Storage)
как писал в прошлом ревью - глобальные переменные не стоит использовать, лучше сделать конструктор и держать мапу внутри структуры, для которой сделать интерфейсные методы

2023-11-07 15:59 UTC, maxlyaptsev commented on internal/app/utils/rand_hex_string_generator.go
> +package utils
1 - неверное название файла
2- можно было бы убрать в пакет services
3 - utils очень абстрактное понятие, лучше обходиться без таких директорий

2023-11-07 17:18 UTC, ilya-burinskiy commented on internal/app/storage/storage.go
> +var storage = make(Storage)
я знаю, что глобальные переменные не стоит использовать, но это же типо база данных. в нее можно писать/читать из любого места программы. имхо добавлять еще по одному аргументу для storage в хэндлерах как то не очень

2023-11-08 17:10 UTC, maxlyaptsev commented on configs/configs.go
> +package configs
лучше в internal перенести этот пакет т.к. он относится непосредственно к проекту. На верхнем уровне может быть cmd, internal, pkg (для пакетов которые можем шарить между другими проектами) и что-то что не относится непосредственно к проекту - например docs, migrations и т.п.

2023-11-08 17:12 UTC, maxlyaptsev commented on internal/app/storage/storage.go
> +var storage = make(Storage)
Ага, в этом и проблема что можно писать/читать из любого места - что будет если сразу из двух мест попытаемся записать данные? Если это внутренняя структура с публичными методами - мы можем поставить блокировки (будет позже в курсе, mutex). А в случае глобальной переменной у нас нет никакого контроля

2023-11-08 17:13 UTC, maxlyaptsev commented on internal/app/storage/storage.go
> +var storage = make(Storage)
Пока можно оставить как есть. Позже будет понятней почему это плохой вариант (когда запустим сервис с проверкой гонки)

2023-11-08 19:15 UTC, merged